/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneuman.node;

import nonneuman.analysis.*;

@SuppressWarnings("nls")
public final class AAIgual extends PAIgual
{
    private TEquals _equals_;
    private PAValor _aValor_;

    public AAIgual()
    {
        // Constructor
    }

    public AAIgual(
        @SuppressWarnings("hiding") TEquals _equals_,
        @SuppressWarnings("hiding") PAValor _aValor_)
    {
        // Constructor
        setEquals(_equals_);

        setAValor(_aValor_);

    }

    @Override
    public Object clone()
    {
        return new AAIgual(
            cloneNode(this._equals_),
            cloneNode(this._aValor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAIgual(this);
    }

    public TEquals getEquals()
    {
        return this._equals_;
    }

    public void setEquals(TEquals node)
    {
        if(this._equals_ != null)
        {
            this._equals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equals_ = node;
    }

    public PAValor getAValor()
    {
        return this._aValor_;
    }

    public void setAValor(PAValor node)
    {
        if(this._aValor_ != null)
        {
            this._aValor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aValor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._equals_)
            + toString(this._aValor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._equals_ == child)
        {
            this._equals_ = null;
            return;
        }

        if(this._aValor_ == child)
        {
            this._aValor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._equals_ == oldChild)
        {
            setEquals((TEquals) newChild);
            return;
        }

        if(this._aValor_ == oldChild)
        {
            setAValor((PAValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
