/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneuman.node;

import nonneuman.analysis.*;

@SuppressWarnings("nls")
public final class AAMaior extends PAMaior
{
    private TGThan _gThan_;
    private PAValor _aValor_;

    public AAMaior()
    {
        // Constructor
    }

    public AAMaior(
        @SuppressWarnings("hiding") TGThan _gThan_,
        @SuppressWarnings("hiding") PAValor _aValor_)
    {
        // Constructor
        setGThan(_gThan_);

        setAValor(_aValor_);

    }

    @Override
    public Object clone()
    {
        return new AAMaior(
            cloneNode(this._gThan_),
            cloneNode(this._aValor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAMaior(this);
    }

    public TGThan getGThan()
    {
        return this._gThan_;
    }

    public void setGThan(TGThan node)
    {
        if(this._gThan_ != null)
        {
            this._gThan_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._gThan_ = node;
    }

    public PAValor getAValor()
    {
        return this._aValor_;
    }

    public void setAValor(PAValor node)
    {
        if(this._aValor_ != null)
        {
            this._aValor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aValor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._gThan_)
            + toString(this._aValor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._gThan_ == child)
        {
            this._gThan_ = null;
            return;
        }

        if(this._aValor_ == child)
        {
            this._aValor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._gThan_ == oldChild)
        {
            setGThan((TGThan) newChild);
            return;
        }

        if(this._aValor_ == oldChild)
        {
            setAValor((PAValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
