/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneuman.node;

import nonneuman.analysis.*;

@SuppressWarnings("nls")
public final class AAMenor extends PAMenor
{
    private TLThan _lThan_;
    private PAValor _aValor_;

    public AAMenor()
    {
        // Constructor
    }

    public AAMenor(
        @SuppressWarnings("hiding") TLThan _lThan_,
        @SuppressWarnings("hiding") PAValor _aValor_)
    {
        // Constructor
        setLThan(_lThan_);

        setAValor(_aValor_);

    }

    @Override
    public Object clone()
    {
        return new AAMenor(
            cloneNode(this._lThan_),
            cloneNode(this._aValor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAMenor(this);
    }

    public TLThan getLThan()
    {
        return this._lThan_;
    }

    public void setLThan(TLThan node)
    {
        if(this._lThan_ != null)
        {
            this._lThan_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lThan_ = node;
    }

    public PAValor getAValor()
    {
        return this._aValor_;
    }

    public void setAValor(PAValor node)
    {
        if(this._aValor_ != null)
        {
            this._aValor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aValor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lThan_)
            + toString(this._aValor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lThan_ == child)
        {
            this._lThan_ = null;
            return;
        }

        if(this._aValor_ == child)
        {
            this._aValor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lThan_ == oldChild)
        {
            setLThan((TLThan) newChild);
            return;
        }

        if(this._aValor_ == oldChild)
        {
            setAValor((PAValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
