/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneuman.node;

import nonneuman.analysis.*;

@SuppressWarnings("nls")
public final class AChamadaAArgumento extends PAArgumento
{
    private PAChamadaFunc _aChamadaFunc_;

    public AChamadaAArgumento()
    {
        // Constructor
    }

    public AChamadaAArgumento(
        @SuppressWarnings("hiding") PAChamadaFunc _aChamadaFunc_)
    {
        // Constructor
        setAChamadaFunc(_aChamadaFunc_);

    }

    @Override
    public Object clone()
    {
        return new AChamadaAArgumento(
            cloneNode(this._aChamadaFunc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAChamadaAArgumento(this);
    }

    public PAChamadaFunc getAChamadaFunc()
    {
        return this._aChamadaFunc_;
    }

    public void setAChamadaFunc(PAChamadaFunc node)
    {
        if(this._aChamadaFunc_ != null)
        {
            this._aChamadaFunc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aChamadaFunc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aChamadaFunc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aChamadaFunc_ == child)
        {
            this._aChamadaFunc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aChamadaFunc_ == oldChild)
        {
            setAChamadaFunc((PAChamadaFunc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
