/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneuman.node;

import nonneuman.analysis.*;

@SuppressWarnings("nls")
public final class ACondicionalAArgumento extends PAArgumento
{
    private PACondicional _aCondicional_;

    public ACondicionalAArgumento()
    {
        // Constructor
    }

    public ACondicionalAArgumento(
        @SuppressWarnings("hiding") PACondicional _aCondicional_)
    {
        // Constructor
        setACondicional(_aCondicional_);

    }

    @Override
    public Object clone()
    {
        return new ACondicionalAArgumento(
            cloneNode(this._aCondicional_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondicionalAArgumento(this);
    }

    public PACondicional getACondicional()
    {
        return this._aCondicional_;
    }

    public void setACondicional(PACondicional node)
    {
        if(this._aCondicional_ != null)
        {
            this._aCondicional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aCondicional_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aCondicional_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aCondicional_ == child)
        {
            this._aCondicional_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aCondicional_ == oldChild)
        {
            setACondicional((PACondicional) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
