/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneuman.node;

import nonneuman.analysis.*;

@SuppressWarnings("nls")
public final class AEqACondicao extends PACondicao
{
    private PAValor _aValor_;
    private PAIgual _aIgual_;

    public AEqACondicao()
    {
        // Constructor
    }

    public AEqACondicao(
        @SuppressWarnings("hiding") PAValor _aValor_,
        @SuppressWarnings("hiding") PAIgual _aIgual_)
    {
        // Constructor
        setAValor(_aValor_);

        setAIgual(_aIgual_);

    }

    @Override
    public Object clone()
    {
        return new AEqACondicao(
            cloneNode(this._aValor_),
            cloneNode(this._aIgual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqACondicao(this);
    }

    public PAValor getAValor()
    {
        return this._aValor_;
    }

    public void setAValor(PAValor node)
    {
        if(this._aValor_ != null)
        {
            this._aValor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aValor_ = node;
    }

    public PAIgual getAIgual()
    {
        return this._aIgual_;
    }

    public void setAIgual(PAIgual node)
    {
        if(this._aIgual_ != null)
        {
            this._aIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aIgual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aValor_)
            + toString(this._aIgual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aValor_ == child)
        {
            this._aValor_ = null;
            return;
        }

        if(this._aIgual_ == child)
        {
            this._aIgual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aValor_ == oldChild)
        {
            setAValor((PAValor) newChild);
            return;
        }

        if(this._aIgual_ == oldChild)
        {
            setAIgual((PAIgual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
