/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneuman.node;

import nonneuman.analysis.*;

@SuppressWarnings("nls")
public final class AFuncaltaAParametro extends PAParametro
{
    private PAFuncAlta _aFuncAlta_;

    public AFuncaltaAParametro()
    {
        // Constructor
    }

    public AFuncaltaAParametro(
        @SuppressWarnings("hiding") PAFuncAlta _aFuncAlta_)
    {
        // Constructor
        setAFuncAlta(_aFuncAlta_);

    }

    @Override
    public Object clone()
    {
        return new AFuncaltaAParametro(
            cloneNode(this._aFuncAlta_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncaltaAParametro(this);
    }

    public PAFuncAlta getAFuncAlta()
    {
        return this._aFuncAlta_;
    }

    public void setAFuncAlta(PAFuncAlta node)
    {
        if(this._aFuncAlta_ != null)
        {
            this._aFuncAlta_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aFuncAlta_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aFuncAlta_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aFuncAlta_ == child)
        {
            this._aFuncAlta_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aFuncAlta_ == oldChild)
        {
            setAFuncAlta((PAFuncAlta) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
