/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneuman.node;

import nonneuman.analysis.*;

@SuppressWarnings("nls")
public final class AIntAValor extends PAValor
{
    private TIntType _intType_;

    public AIntAValor()
    {
        // Constructor
    }

    public AIntAValor(
        @SuppressWarnings("hiding") TIntType _intType_)
    {
        // Constructor
        setIntType(_intType_);

    }

    @Override
    public Object clone()
    {
        return new AIntAValor(
            cloneNode(this._intType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntAValor(this);
    }

    public TIntType getIntType()
    {
        return this._intType_;
    }

    public void setIntType(TIntType node)
    {
        if(this._intType_ != null)
        {
            this._intType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._intType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._intType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._intType_ == child)
        {
            this._intType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._intType_ == oldChild)
        {
            setIntType((TIntType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
