/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneuman.node;

import nonneuman.analysis.*;

@SuppressWarnings("nls")
public final class AOp1AInicio extends PAInicio
{
    private PABlocoList _aBlocoList_;
    private PAMain _aMain_;

    public AOp1AInicio()
    {
        // Constructor
    }

    public AOp1AInicio(
        @SuppressWarnings("hiding") PABlocoList _aBlocoList_,
        @SuppressWarnings("hiding") PAMain _aMain_)
    {
        // Constructor
        setABlocoList(_aBlocoList_);

        setAMain(_aMain_);

    }

    @Override
    public Object clone()
    {
        return new AOp1AInicio(
            cloneNode(this._aBlocoList_),
            cloneNode(this._aMain_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOp1AInicio(this);
    }

    public PABlocoList getABlocoList()
    {
        return this._aBlocoList_;
    }

    public void setABlocoList(PABlocoList node)
    {
        if(this._aBlocoList_ != null)
        {
            this._aBlocoList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aBlocoList_ = node;
    }

    public PAMain getAMain()
    {
        return this._aMain_;
    }

    public void setAMain(PAMain node)
    {
        if(this._aMain_ != null)
        {
            this._aMain_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aMain_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aBlocoList_)
            + toString(this._aMain_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aBlocoList_ == child)
        {
            this._aBlocoList_ = null;
            return;
        }

        if(this._aMain_ == child)
        {
            this._aMain_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aBlocoList_ == oldChild)
        {
            setABlocoList((PABlocoList) newChild);
            return;
        }

        if(this._aMain_ == oldChild)
        {
            setAMain((PAMain) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
