/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneuman.node;

import nonneuman.analysis.*;

@SuppressWarnings("nls")
public final class AOp3AInicio extends PAInicio
{
    private PAMain _aMain_;

    public AOp3AInicio()
    {
        // Constructor
    }

    public AOp3AInicio(
        @SuppressWarnings("hiding") PAMain _aMain_)
    {
        // Constructor
        setAMain(_aMain_);

    }

    @Override
    public Object clone()
    {
        return new AOp3AInicio(
            cloneNode(this._aMain_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOp3AInicio(this);
    }

    public PAMain getAMain()
    {
        return this._aMain_;
    }

    public void setAMain(PAMain node)
    {
        if(this._aMain_ != null)
        {
            this._aMain_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aMain_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aMain_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aMain_ == child)
        {
            this._aMain_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aMain_ == oldChild)
        {
            setAMain((PAMain) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
