/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneuman.node;

import nonneuman.analysis.*;

@SuppressWarnings("nls")
public final class ARealAValor extends PAValor
{
    private TRealType _realType_;

    public ARealAValor()
    {
        // Constructor
    }

    public ARealAValor(
        @SuppressWarnings("hiding") TRealType _realType_)
    {
        // Constructor
        setRealType(_realType_);

    }

    @Override
    public Object clone()
    {
        return new ARealAValor(
            cloneNode(this._realType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARealAValor(this);
    }

    public TRealType getRealType()
    {
        return this._realType_;
    }

    public void setRealType(TRealType node)
    {
        if(this._realType_ != null)
        {
            this._realType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._realType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._realType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._realType_ == child)
        {
            this._realType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._realType_ == oldChild)
        {
            setRealType((TRealType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
