/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneuman.node;

import nonneuman.analysis.*;

@SuppressWarnings("nls")
public final class AUnicoAArgsList extends PAArgsList
{
    private PAArgumento _aArgumento_;

    public AUnicoAArgsList()
    {
        // Constructor
    }

    public AUnicoAArgsList(
        @SuppressWarnings("hiding") PAArgumento _aArgumento_)
    {
        // Constructor
        setAArgumento(_aArgumento_);

    }

    @Override
    public Object clone()
    {
        return new AUnicoAArgsList(
            cloneNode(this._aArgumento_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnicoAArgsList(this);
    }

    public PAArgumento getAArgumento()
    {
        return this._aArgumento_;
    }

    public void setAArgumento(PAArgumento node)
    {
        if(this._aArgumento_ != null)
        {
            this._aArgumento_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aArgumento_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aArgumento_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aArgumento_ == child)
        {
            this._aArgumento_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aArgumento_ == oldChild)
        {
            setAArgumento((PAArgumento) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
