/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneuman.node;

import nonneuman.analysis.*;

@SuppressWarnings("nls")
public final class AVariosABlocoList extends PABlocoList
{
    private PABloco _aBloco_;
    private PABlocoList _blocos_;

    public AVariosABlocoList()
    {
        // Constructor
    }

    public AVariosABlocoList(
        @SuppressWarnings("hiding") PABloco _aBloco_,
        @SuppressWarnings("hiding") PABlocoList _blocos_)
    {
        // Constructor
        setABloco(_aBloco_);

        setBlocos(_blocos_);

    }

    @Override
    public Object clone()
    {
        return new AVariosABlocoList(
            cloneNode(this._aBloco_),
            cloneNode(this._blocos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariosABlocoList(this);
    }

    public PABloco getABloco()
    {
        return this._aBloco_;
    }

    public void setABloco(PABloco node)
    {
        if(this._aBloco_ != null)
        {
            this._aBloco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aBloco_ = node;
    }

    public PABlocoList getBlocos()
    {
        return this._blocos_;
    }

    public void setBlocos(PABlocoList node)
    {
        if(this._blocos_ != null)
        {
            this._blocos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blocos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aBloco_)
            + toString(this._blocos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aBloco_ == child)
        {
            this._aBloco_ = null;
            return;
        }

        if(this._blocos_ == child)
        {
            this._blocos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aBloco_ == oldChild)
        {
            setABloco((PABloco) newChild);
            return;
        }

        if(this._blocos_ == oldChild)
        {
            setBlocos((PABlocoList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
