/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneuman.node;

import nonneuman.analysis.*;

@SuppressWarnings("nls")
public final class AVariosATypeList extends PATypeList
{
    private PAType _aType_;
    private TComma _comma_;
    private PATypeList _types_;

    public AVariosATypeList()
    {
        // Constructor
    }

    public AVariosATypeList(
        @SuppressWarnings("hiding") PAType _aType_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PATypeList _types_)
    {
        // Constructor
        setAType(_aType_);

        setComma(_comma_);

        setTypes(_types_);

    }

    @Override
    public Object clone()
    {
        return new AVariosATypeList(
            cloneNode(this._aType_),
            cloneNode(this._comma_),
            cloneNode(this._types_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariosATypeList(this);
    }

    public PAType getAType()
    {
        return this._aType_;
    }

    public void setAType(PAType node)
    {
        if(this._aType_ != null)
        {
            this._aType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aType_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PATypeList getTypes()
    {
        return this._types_;
    }

    public void setTypes(PATypeList node)
    {
        if(this._types_ != null)
        {
            this._types_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._types_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aType_)
            + toString(this._comma_)
            + toString(this._types_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aType_ == child)
        {
            this._aType_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._types_ == child)
        {
            this._types_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aType_ == oldChild)
        {
            setAType((PAType) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._types_ == oldChild)
        {
            setTypes((PATypeList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
