/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneuman.node;

import nonneuman.analysis.*;

@SuppressWarnings("nls")
public final class TEntryPoint extends Token
{
    public TEntryPoint()
    {
        super.setText("entry");
    }

    public TEntryPoint(int line, int pos)
    {
        super.setText("entry");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEntryPoint(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEntryPoint(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEntryPoint text.");
    }
}
