/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneuman.node;

import nonneuman.analysis.*;

@SuppressWarnings("nls")
public final class TFuncId extends Token
{
    public TFuncId()
    {
        super.setText("function");
    }

    public TFuncId(int line, int pos)
    {
        super.setText("function");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFuncId(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFuncId(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFuncId text.");
    }
}
